version: '3'
services:
  app:
    build: ./app
    container_name: coodesh_app
    ports:
      - 5173:5173

  api:
    build: ./api
    container_name: coodesh_api
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: coodesh_db
    networks:
      - app-network

  database:
    image: mysql:latest
    container_name: coodesh_db
    restart: always 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coodesh_db
    volumes:
      - ./.mysql/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
